### ISSUE TITLE
Issue with $j in end time? (JavaScript implementation)

### ISSUE THREAD

**Issue by ericthewizard** [hapi-server/uri-templates#23]
I was just testing the JS implementation and ran into a potential problem:

```javascript
const filename = "ac27_crn1926_199722300-199725000.gif";
const template = "ac27_crn$x_$Y$j00-$(Y;end)$(j;end)00.gif"

ut = new URITemplate(template);

console.log(ut.parse(filename));
```

Prints:

```javascript
[1997, 8, 11, 0, 0, 0, 0, 1997, 1, 250, 0, 0, 0, 0]
```

So it gets the month/day of month correct for the start time, but is still using the DOY with month = 1 for the end time.

**Comment by jbfaden** [comment]
Thanks for pointing this out.  This same error is likely in the Java and Python implementations, since I use a code conversion to make the JavaScript version.  I can look at this right now.

**Comment by jbfaden** [comment]
The test URITemplateTest.testParse tests this now, and the Java version is fixed.  Now converting to Python and JavaScript.

**Comment by ericthewizard** [comment]
Thanks!

**Comment by jbfaden** [comment]
It's passing the JavaScript tests, so I think it's good now.  (Incidentally do you know how to do unit testing in JavaScript?  I kludged something up, and I can see it's testing the new code.)

**Comment by ericthewizard** [comment]
I've been using Jest:

https://jestjs.io

Very easy to get started and add new test cases!

Thanks again!

**Comment by jbfaden** [comment]
I'll have a look.  (Especially if I can ask you questions!)

**Comment by ericthewizard** [comment]
> I'll have a look. (Especially if I can ask you questions!)

Absolutely! In case you're not aware, my new email is eric.grimes at nasa.gov (note: my UCLA email isn't checked anymore, so please don't send any questions there!)

**Comment by ericthewizard** [comment]
When you get a chance, can you update the Python version as well (with this fix)? I'm still running into this issue there:

```python

>>> test_file = "https://spdf.gsfc.nasa.gov/pub/pre_generated_plots/kp_plots/ace/gif/ac_199733000-199733100.gif"
>>> digits = ut.parse(test_file, {})
>>> digits
[1997, 11, 26, 0, 0, 0, 0, 1997, 1, 331, 0, 0, 0, 0]
```

**Comment by jbfaden** [comment]
Weird that I didn't get it back in December.  I'll fix it now.  Thanks for pointing this out.

**Comment by ericthewizard** [comment]
Thanks! Definitely working for me now. I'm not sure if it's in PyPI - I'm downloading the zip from GifHub
