### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ericthewizard** [hapi-server/uri-templates#24]
I'm thinking of using the JavaScript implementation in our new gif_walk tool at SPDF, but noticed there isn't a license yet (or one that I could find). Can we add a license (preferably something FOSS)?

**Comment by jbfaden** [comment]
I would just assume use GPL3, or do you have any other preference?

**Comment by candeynasa** [comment]
Use the Apache 2 license.  Thanx

From: Eric ***@***.***>
Reply-To: hapi-server/uri-templates ***@***.***>
Date: Wednesday, December 6, 2023 at 13:46
To: hapi-server/uri-templates ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [BULK] [hapi-server/uri-templates] License? (Issue #24)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



I'm thinking of using the JavaScript implementation in our new gif_walk tool at SPDF, but noticed there isn't a license yet (or one that I could find). Can we add a license (preferably something FOSS)?

**Comment by ericthewizard** [comment]
Thanks - works for me!

**Comment by candeynasa** [comment]
Please use the Apache 2 license for government work.  GPL is not suitable for open science software and incompatible with mixing with other packages.

**Comment by ericthewizard** [comment]
Thanks!
