### ISSUE TITLE
Case/fmt modifiers not working

### ISSUE THREAD

**Issue by ericthewizard** [hapi-server/uri-templates#27]
According to the spec, you can specify the case using modifiers:

> fmt=abbrev|full - (optional); default=abbrev
> case=lc|uc|cap - (optional); default=lc
> Possibilities:
> $(b;fmt=abbrev;case=lc): jan, feb, ...
> $(b;fmt=abbrev;case=uc): JAN, FEB, ...
> $(b;fmt=abbrev;case=cap): Jan, Feb, ...
> $(b;fmt=full;case=lc): january, february, ...
> $(b;fmt=full;case=cap): JANUARY, FEBRUARY, ...
> $(b;fmt=full;case=uc): January, February, ...

Note: in the spec, "cap" and "uc" are flipped for the full and abbreviated cases. 

More importantly, these don't seem to work for me (in Python or JavaScript); here's an example in Python, e.g., lower case:

```python
from URITemplate import URITemplate
from datetime import datetime

month = "$(b;case=lc)"
ut = URITemplate(month)

now = datetime.now()
ut.format(now.isoformat(), now.isoformat())
```

Gives:
> 'Feb'

`fmt` doesn't seem to be working either:

```python
month = "$(b;fmt=full;case=lc)"
ut = URITemplate(month)
ut.format(now.isoformat(), now.isoformat())
```

Gives:

> 'Feb'

**Comment by ericthewizard** [comment]
Have you had a chance to look into this one yet? I thought about making a kludge to get it to work in my copy of the JS version, but that would get us out of sync

**Comment by jbfaden** [comment]
Hi Eric, sorry I missed this one.  I'll have a look in the morning.

**Comment by jbfaden** [comment]
I have this coded in the Java version, now I need to convert to Python and JavaScript.

**Comment by ericthewizard** [comment]
> I have this coded in the Java version, now I need to convert to Python and JavaScript.

Thanks!

**Comment by jbfaden** [comment]
It should be ready now, where it's passing the unit tests on Python.  Let me know if you see anything weird!  I still need to do the JavaScript version, but I assume you are not using it.  I'll do that tomorrow morning.

**Comment by ericthewizard** [comment]
I'm using both the JavaScript and Python versions. I'll test them out tomorrow. 

Thanks again!
